const mongoose = require('mongoose');

const slug = require('mongoose-slug-updater');

mongoose.plugin(slug);

const trackSchema = new mongoose.Schema(
  {
    // ==========================================
    // BE-3: METADATA ENGINE & VISUALS
    // ==========================================
    title: {
      type: String,
      required: [true, 'A track must have a title'],
      trim: true,
      maxlength: [100, 'Title cannot exceed 100 characters'],
    },
    permalink: {
      type: String,
      unique: true,
      sparse: true,
      trim: true,
      slug: 'title', // <--- 3. THIS IS THE MAGIC LINE!
      slugPaddingSize: 1,
      index: true, // Add an index for faster lookups by permalink
    },
    description: {
      type: String,
      maxlength: [1000, 'Description cannot exceed 1000 characters'],
      trim: true,
    },
    genre: {
      type: String,
      trim: true,
    },
    tags: [
      {
        type: String,
        trim: true,
      },
    ],
    releaseDate: {
      type: Date,
      default: Date.now,
    },
    artworkUrl: {
      type: String,
      default: 'default-track-artwork.png', // Will be replaced by your Azure Blob URL
    },
    waveform: {
      type: [Number], // We will store the data points generated by ffmpeg here
      default: [],
    },

    // ==========================================
    // BE-3: TRACK VISIBILITY
    // ==========================================
    isPublic: {
      type: Boolean,
      default: true, // true = Public (searchable), false = Private (link-only)
    },

    // ==========================================
    // BE-2: AUDIO PIPELINE (Placeholders)
    // ==========================================
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    audioUrl: {
      type: String, // Azure Blob URL for the audio file
    },
    duration: {
      type: Number, // In seconds
    },
    status: {
      type: String,
      enum: ['Processing', 'Finished', 'Failed'],
      default: 'Processing',
    },
  },
  { timestamps: true }
);

// Mongoose Pre-save hook to auto-generate the permalink from the title

const Track = mongoose.model('Track', trackSchema);
module.exports = Track;
